
from PyQt5 import QtCore, QtGui, QtWidgets







class Ui_Butelka(object):
    def setupUi(self, MainWindow):
    
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
 
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.Butelka = QtWidgets.QWidget()
        self.Butelka.setObjectName("Butelka")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Butelka)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 270, 411, 561))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setRowCount(17)
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setObjectName("tableWidget_3")
        
        self.layoutWidget7 = QtWidgets.QWidget(self.Butelka)
        self.layoutWidget7.setGeometry(QtCore.QRect(700, 110, 370, 31))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        
        self.label_23 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_5.addWidget(self.label_23)
        
        self.label_24 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: red; font-size: 20px; font-family: Arial;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_5.addWidget(self.label_24)
        
 
        self.layoutWidget_6 = QtWidgets.QWidget(self.Butelka)
        self.layoutWidget_6.setGeometry(QtCore.QRect(700, 150, 380, 160))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_6)
    
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setText("")
        self.label_43.setStyleSheet("color: red; font-size: 20px; font-family: Arial;")
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 0, 1, 1, 2)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_6)
    
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 2, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_6)
    
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("color: red; font-size: 20px; font-family: Arial;")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 2, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_6)
    
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 2, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_6)
        
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_5.addWidget(self.pushButton_17, 3, 1, 1, 2)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("color: red; font-size: 20px; font-family: Arial;")
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 1, 1, 1, 2)
        self.label_52 = QtWidgets.QLabel(self.Butelka)
        self.label_52.setGeometry(QtCore.QRect(300, 20, 401, 51))

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.Butelka)
        self.label_53.setGeometry(QtCore.QRect(0, 0, 291, 111))

        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("image/imge_pet_ring.png"))
        self.label_53.setScaledContents(True)
        self.label_53.setObjectName("label_53")
        self.layoutWidget_7 = QtWidgets.QWidget(self.Butelka)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 210, 411, 30))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_7)
    
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_13.addWidget(self.label_54)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_7)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_13.addWidget(self.lineEdit_6)
        self.layoutWidget_8 = QtWidgets.QWidget(self.Butelka)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 150, 645, 31))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        
        self.comboBox_25 = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_25.setEditable(True)
        # Налаштовуємо пошук та вибір з клавіатури
        
        completer = QtWidgets.QCompleter(self.comboBox_25.model(), self.comboBox_25)
        completer.setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        completer.setFilterMode(QtCore.Qt.MatchContains)  # Можна змінити спосіб фільтрації
        completer.setCaseSensitivity(QtCore.Qt.CaseInsensitive)  # Враховувати регістр
        
        self.comboBox_25.setCompleter(completer)
        
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_25.setFont(font)
        self.comboBox_25.setObjectName("comboBox_25")
        self.horizontalLayout_14.addWidget(self.comboBox_25)
        self.comboBox_26 = QtWidgets.QComboBox(self.layoutWidget_8)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_26.setFont(font)
        self.comboBox_26.setObjectName("comboBox_26")
        self.horizontalLayout_14.addWidget(self.comboBox_26)
        self.comboBox_27 = QtWidgets.QComboBox(self.layoutWidget_8)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_27.setFont(font)
        self.comboBox_27.setObjectName("comboBox_27")
        self.horizontalLayout_14.addWidget(self.comboBox_27)
        self.comboBox_28 = QtWidgets.QComboBox(self.layoutWidget_8)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_28.setFont(font)
        self.comboBox_28.setObjectName("comboBox_28")
        self.horizontalLayout_14.addWidget(self.comboBox_28)
        
        self.comboBox_29 = QtWidgets.QComboBox(self.layoutWidget_8)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_29.setFont(font)
        self.comboBox_29.setObjectName("comboBox_29")
        
        self.comboBox_29.setEditable(True)
        
        completer = QtWidgets.QCompleter(self.comboBox_29.model(), self.comboBox_29)
        completer.setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        completer.setFilterMode(QtCore.Qt.MatchContains)  # Можна змінити спосіб фільтрації
        completer.setCaseSensitivity(QtCore.Qt.CaseInsensitive)  # Враховувати регістр
        
        self.comboBox_29.setCompleter(completer)
        self.horizontalLayout_14.addWidget(self.comboBox_29)
        
        self.comboBox_30 = QtWidgets.QComboBox(self.layoutWidget_8)

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_30.setFont(font)
        self.comboBox_30.setObjectName("comboBox_30")
        self.horizontalLayout_14.addWidget(self.comboBox_30)
        self.layoutWidget_9 = QtWidgets.QWidget(self.Butelka)
        self.layoutWidget_9.setGeometry(QtCore.QRect(700, 20, 375, 31))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_15.addWidget(self.label_55)
        
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setStyleSheet("color: red; font-size: 20px; font-family: Arial;")
        self.label_56.setText("")
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_15.addWidget(self.label_56)
        
        self.layoutWidget_10 = QtWidgets.QWidget(self.Butelka)
        self.layoutWidget_10.setGeometry(QtCore.QRect(870, 700, 211, 131))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_10)
        
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_10)
        
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_10)
        
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_5.addWidget(self.pushButton_20)
        self.layout.addWidget(self.Butelka)
        
        self.widget = QtWidgets.QWidget(self.Butelka)
        self.widget.setGeometry(QtCore.QRect(460, 210, 201, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        
        self.comboBox_7 = QtWidgets.QComboBox(self.widget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_2.addWidget(self.comboBox_7)
        
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.comboBox_8 = QtWidgets.QComboBox(self.widget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.verticalLayout_2.addWidget(self.comboBox_8)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.comboBox_9 = QtWidgets.QComboBox(self.widget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.verticalLayout_2.addWidget(self.comboBox_9)
        
        self.widget = QtWidgets.QWidget(self.Butelka)
        self.widget.setGeometry(QtCore.QRect(460, 500, 231, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setText("")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
       

        
        
        _translate = QtCore.QCoreApplication.translate
        self.label_23.setText(_translate("MainWindow", "EUR/PLN"))
        self.label_42.setText(_translate("MainWindow", "Cena PET (EUR/Ton)"))
        self.label_47.setText(_translate("MainWindow", "Cena R-PET (EUR/Ton)"))
        self.label_48.setText(_translate("MainWindow", "Narzut"))
        self.label_50.setText(_translate("MainWindow", "%"))
        self.pushButton_17.setText(_translate("MainWindow", "Update"))
        self.label_52.setText(_translate("MainWindow", "Index"))
        self.label_54.setText(_translate("MainWindow", "Ilosc dla Klienta"))
        self.lineEdit_6.setText(_translate("MainWindow", "100000"))
        self.label_55.setText(_translate("MainWindow", "Data aktualizacji bazy"))
        self.pushButton_18.setText(_translate("MainWindow", "Create Cost"))
        self.pushButton_19.setText(_translate("MainWindow", "Create Excel"))
        self.pushButton_20.setText(_translate("MainWindow", "Coming soon"))
        self.label_13.setText(_translate("MainWindow", "Choose the pallet height"))
        self.label_14.setText(_translate("MainWindow", "Choose Packing Method"))
        self.label_15.setText(_translate("MainWindow", "What Pallet ?"))
        self.checkBox.setText(_translate("MainWindow", "Foil Cap"))
        self.checkBox_2.setText(_translate("MainWindow", "Additionally stretch"))
        self.checkBox_3.setText(_translate("MainWindow", "Tracer for separation"))
        self.checkBox_4.setText(_translate("MainWindow", "Corner"))
        self.checkBox_5.setText(_translate("MainWindow", "Banding tapes"))
        self.checkBox_6.setText(_translate("MainWindow", "Client special request"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Cost Special Request "))

        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)

        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
